'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Linq

Partial Public Class agencia_viajes_condorEntities1
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=agencia_viajes_condorEntities1")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub


    Public Overridable Function AgregarCliente(nombres As String, apellidos As String, email As String, dpi As String, direccion As String, telefono As String, nacimiento As String, nit As String) As ObjectResult(Of Nullable(Of Integer))
        Dim nombresParameter As ObjectParameter = If(nombres IsNot Nothing, New ObjectParameter("nombres", nombres), New ObjectParameter("nombres", GetType(String)))

        Dim apellidosParameter As ObjectParameter = If(apellidos IsNot Nothing, New ObjectParameter("apellidos", apellidos), New ObjectParameter("apellidos", GetType(String)))

        Dim emailParameter As ObjectParameter = If(email IsNot Nothing, New ObjectParameter("email", email), New ObjectParameter("email", GetType(String)))

        Dim dpiParameter As ObjectParameter = If(dpi IsNot Nothing, New ObjectParameter("dpi", dpi), New ObjectParameter("dpi", GetType(String)))

        Dim direccionParameter As ObjectParameter = If(direccion IsNot Nothing, New ObjectParameter("direccion", direccion), New ObjectParameter("direccion", GetType(String)))

        Dim telefonoParameter As ObjectParameter = If(telefono IsNot Nothing, New ObjectParameter("telefono", telefono), New ObjectParameter("telefono", GetType(String)))

        Dim nacimientoParameter As ObjectParameter = If(nacimiento IsNot Nothing, New ObjectParameter("nacimiento", nacimiento), New ObjectParameter("nacimiento", GetType(String)))

        Dim nitParameter As ObjectParameter = If(nit IsNot Nothing, New ObjectParameter("nit", nit), New ObjectParameter("nit", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of Nullable(Of Integer))("AgregarCliente", nombresParameter, apellidosParameter, emailParameter, dpiParameter, direccionParameter, telefonoParameter, nacimientoParameter, nitParameter)
    End Function

    Public Overridable Function buscarCliente(dpi As String) As ObjectResult(Of buscarCliente_Result)
        Dim dpiParameter As ObjectParameter = If(dpi IsNot Nothing, New ObjectParameter("dpi", dpi), New ObjectParameter("dpi", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of buscarCliente_Result)("buscarCliente", dpiParameter)
    End Function

    Public Overridable Function destinos(query As String) As ObjectResult(Of destinos_Result)
        Dim queryParameter As ObjectParameter = If(query IsNot Nothing, New ObjectParameter("query", query), New ObjectParameter("query", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of destinos_Result)("destinos", queryParameter)
    End Function

    Public Overridable Function detalleVuelo(vuelo As String) As ObjectResult(Of detalleVuelo_Result)
        Dim vueloParameter As ObjectParameter = If(vuelo IsNot Nothing, New ObjectParameter("vuelo", vuelo), New ObjectParameter("vuelo", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of detalleVuelo_Result)("detalleVuelo", vueloParameter)
    End Function

    Public Overridable Function Facturar(reservacion As Nullable(Of Integer), fecha As String, t_pago As Nullable(Of Integer), efectivo As String, credito As String, debito As String, cliente As Nullable(Of Integer)) As ObjectResult(Of Nullable(Of Integer))
        Dim reservacionParameter As ObjectParameter = If(reservacion.HasValue, New ObjectParameter("reservacion", reservacion), New ObjectParameter("reservacion", GetType(Integer)))

        Dim fechaParameter As ObjectParameter = If(fecha IsNot Nothing, New ObjectParameter("fecha", fecha), New ObjectParameter("fecha", GetType(String)))

        Dim t_pagoParameter As ObjectParameter = If(t_pago.HasValue, New ObjectParameter("t_pago", t_pago), New ObjectParameter("t_pago", GetType(Integer)))

        Dim efectivoParameter As ObjectParameter = If(efectivo IsNot Nothing, New ObjectParameter("efectivo", efectivo), New ObjectParameter("efectivo", GetType(String)))

        Dim creditoParameter As ObjectParameter = If(credito IsNot Nothing, New ObjectParameter("credito", credito), New ObjectParameter("credito", GetType(String)))

        Dim debitoParameter As ObjectParameter = If(debito IsNot Nothing, New ObjectParameter("debito", debito), New ObjectParameter("debito", GetType(String)))

        Dim clienteParameter As ObjectParameter = If(cliente.HasValue, New ObjectParameter("cliente", cliente), New ObjectParameter("cliente", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of Nullable(Of Integer))("Facturar", reservacionParameter, fechaParameter, t_pagoParameter, efectivoParameter, creditoParameter, debitoParameter, clienteParameter)
    End Function

    Public Overridable Function facturar_vuelo_economico(reservacion As Nullable(Of Integer), fecha As String, t_pago As Nullable(Of Integer), efectivo As String, credito As String, debito As String, cliente As Nullable(Of Integer)) As ObjectResult(Of Nullable(Of Integer))
        Dim reservacionParameter As ObjectParameter = If(reservacion.HasValue, New ObjectParameter("reservacion", reservacion), New ObjectParameter("reservacion", GetType(Integer)))

        Dim fechaParameter As ObjectParameter = If(fecha IsNot Nothing, New ObjectParameter("fecha", fecha), New ObjectParameter("fecha", GetType(String)))

        Dim t_pagoParameter As ObjectParameter = If(t_pago.HasValue, New ObjectParameter("t_pago", t_pago), New ObjectParameter("t_pago", GetType(Integer)))

        Dim efectivoParameter As ObjectParameter = If(efectivo IsNot Nothing, New ObjectParameter("efectivo", efectivo), New ObjectParameter("efectivo", GetType(String)))

        Dim creditoParameter As ObjectParameter = If(credito IsNot Nothing, New ObjectParameter("credito", credito), New ObjectParameter("credito", GetType(String)))

        Dim debitoParameter As ObjectParameter = If(debito IsNot Nothing, New ObjectParameter("debito", debito), New ObjectParameter("debito", GetType(String)))

        Dim clienteParameter As ObjectParameter = If(cliente.HasValue, New ObjectParameter("cliente", cliente), New ObjectParameter("cliente", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of Nullable(Of Integer))("facturar_vuelo_economico", reservacionParameter, fechaParameter, t_pagoParameter, efectivoParameter, creditoParameter, debitoParameter, clienteParameter)
    End Function

    Public Overridable Function facturar_vuelo_primera_clase(reservacion As Nullable(Of Integer), fecha As String, t_pago As Nullable(Of Integer), efectivo As String, credito As String, debito As String, cliente As Nullable(Of Integer)) As ObjectResult(Of Nullable(Of Integer))
        Dim reservacionParameter As ObjectParameter = If(reservacion.HasValue, New ObjectParameter("reservacion", reservacion), New ObjectParameter("reservacion", GetType(Integer)))

        Dim fechaParameter As ObjectParameter = If(fecha IsNot Nothing, New ObjectParameter("fecha", fecha), New ObjectParameter("fecha", GetType(String)))

        Dim t_pagoParameter As ObjectParameter = If(t_pago.HasValue, New ObjectParameter("t_pago", t_pago), New ObjectParameter("t_pago", GetType(Integer)))

        Dim efectivoParameter As ObjectParameter = If(efectivo IsNot Nothing, New ObjectParameter("efectivo", efectivo), New ObjectParameter("efectivo", GetType(String)))

        Dim creditoParameter As ObjectParameter = If(credito IsNot Nothing, New ObjectParameter("credito", credito), New ObjectParameter("credito", GetType(String)))

        Dim debitoParameter As ObjectParameter = If(debito IsNot Nothing, New ObjectParameter("debito", debito), New ObjectParameter("debito", GetType(String)))

        Dim clienteParameter As ObjectParameter = If(cliente.HasValue, New ObjectParameter("cliente", cliente), New ObjectParameter("cliente", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of Nullable(Of Integer))("facturar_vuelo_primera_clase", reservacionParameter, fechaParameter, t_pagoParameter, efectivoParameter, creditoParameter, debitoParameter, clienteParameter)
    End Function

    Public Overridable Function lista_hotel(destino As Nullable(Of Integer), doble As Nullable(Of Integer), simple As Nullable(Of Integer)) As ObjectResult(Of lista_hotel_Result)
        Dim destinoParameter As ObjectParameter = If(destino.HasValue, New ObjectParameter("destino", destino), New ObjectParameter("destino", GetType(Integer)))

        Dim dobleParameter As ObjectParameter = If(doble.HasValue, New ObjectParameter("doble", doble), New ObjectParameter("doble", GetType(Integer)))

        Dim simpleParameter As ObjectParameter = If(simple.HasValue, New ObjectParameter("simple", simple), New ObjectParameter("simple", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of lista_hotel_Result)("lista_hotel", destinoParameter, dobleParameter, simpleParameter)
    End Function

    Public Overridable Function listar_cruceros(puerto As Nullable(Of Integer), fecha As String, pasajeros As Nullable(Of Integer)) As ObjectResult(Of listar_cruceros_Result)
        Dim puertoParameter As ObjectParameter = If(puerto.HasValue, New ObjectParameter("puerto", puerto), New ObjectParameter("puerto", GetType(Integer)))

        Dim fechaParameter As ObjectParameter = If(fecha IsNot Nothing, New ObjectParameter("fecha", fecha), New ObjectParameter("fecha", GetType(String)))

        Dim pasajerosParameter As ObjectParameter = If(pasajeros.HasValue, New ObjectParameter("pasajeros", pasajeros), New ObjectParameter("pasajeros", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of listar_cruceros_Result)("listar_cruceros", puertoParameter, fechaParameter, pasajerosParameter)
    End Function

    Public Overridable Function login(pass As String, user As String) As ObjectResult(Of login_Result)
        Dim passParameter As ObjectParameter = If(pass IsNot Nothing, New ObjectParameter("pass", pass), New ObjectParameter("pass", GetType(String)))

        Dim userParameter As ObjectParameter = If(user IsNot Nothing, New ObjectParameter("user", user), New ObjectParameter("user", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of login_Result)("login", passParameter, userParameter)
    End Function

    Public Overridable Function obtenerReservacion(codigo As String) As ObjectResult(Of Nullable(Of Integer))
        Dim codigoParameter As ObjectParameter = If(codigo IsNot Nothing, New ObjectParameter("codigo", codigo), New ObjectParameter("codigo", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of Nullable(Of Integer))("obtenerReservacion", codigoParameter)
    End Function

    Public Overridable Function reservar_crucero(usuario As Nullable(Of Integer), crucero As Nullable(Of Integer), pasajeros As Nullable(Of Integer)) As ObjectResult(Of Nullable(Of Integer))
        Dim usuarioParameter As ObjectParameter = If(usuario.HasValue, New ObjectParameter("usuario", usuario), New ObjectParameter("usuario", GetType(Integer)))

        Dim cruceroParameter As ObjectParameter = If(crucero.HasValue, New ObjectParameter("crucero", crucero), New ObjectParameter("crucero", GetType(Integer)))

        Dim pasajerosParameter As ObjectParameter = If(pasajeros.HasValue, New ObjectParameter("pasajeros", pasajeros), New ObjectParameter("pasajeros", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of Nullable(Of Integer))("reservar_crucero", usuarioParameter, cruceroParameter, pasajerosParameter)
    End Function

    Public Overridable Function reservar_vuelo_Hotel_e(destino As Nullable(Of Integer), vuelo As Nullable(Of Integer), pasajeros As Nullable(Of Integer), desayuno As Nullable(Of Integer), habitacion_s As Nullable(Of Integer), habitacion_d As Nullable(Of Integer), hotel As Nullable(Of Integer), usuario As Nullable(Of Integer)) As ObjectResult(Of Nullable(Of Integer))
        Dim destinoParameter As ObjectParameter = If(destino.HasValue, New ObjectParameter("destino", destino), New ObjectParameter("destino", GetType(Integer)))

        Dim vueloParameter As ObjectParameter = If(vuelo.HasValue, New ObjectParameter("vuelo", vuelo), New ObjectParameter("vuelo", GetType(Integer)))

        Dim pasajerosParameter As ObjectParameter = If(pasajeros.HasValue, New ObjectParameter("pasajeros", pasajeros), New ObjectParameter("pasajeros", GetType(Integer)))

        Dim desayunoParameter As ObjectParameter = If(desayuno.HasValue, New ObjectParameter("desayuno", desayuno), New ObjectParameter("desayuno", GetType(Integer)))

        Dim habitacion_sParameter As ObjectParameter = If(habitacion_s.HasValue, New ObjectParameter("habitacion_s", habitacion_s), New ObjectParameter("habitacion_s", GetType(Integer)))

        Dim habitacion_dParameter As ObjectParameter = If(habitacion_d.HasValue, New ObjectParameter("habitacion_d", habitacion_d), New ObjectParameter("habitacion_d", GetType(Integer)))

        Dim hotelParameter As ObjectParameter = If(hotel.HasValue, New ObjectParameter("hotel", hotel), New ObjectParameter("hotel", GetType(Integer)))

        Dim usuarioParameter As ObjectParameter = If(usuario.HasValue, New ObjectParameter("usuario", usuario), New ObjectParameter("usuario", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of Nullable(Of Integer))("reservar_vuelo_Hotel_e", destinoParameter, vueloParameter, pasajerosParameter, desayunoParameter, habitacion_sParameter, habitacion_dParameter, hotelParameter, usuarioParameter)
    End Function

    Public Overridable Function reservar_vuelo_Hotel_p(destino As Nullable(Of Integer), vuelo As Nullable(Of Integer), pasajeros As Nullable(Of Integer), desayuno As Nullable(Of Integer), habitacion_s As Nullable(Of Integer), habitacion_d As Nullable(Of Integer), hotel As Nullable(Of Integer), usuario As Nullable(Of Integer)) As ObjectResult(Of Nullable(Of Integer))
        Dim destinoParameter As ObjectParameter = If(destino.HasValue, New ObjectParameter("destino", destino), New ObjectParameter("destino", GetType(Integer)))

        Dim vueloParameter As ObjectParameter = If(vuelo.HasValue, New ObjectParameter("vuelo", vuelo), New ObjectParameter("vuelo", GetType(Integer)))

        Dim pasajerosParameter As ObjectParameter = If(pasajeros.HasValue, New ObjectParameter("pasajeros", pasajeros), New ObjectParameter("pasajeros", GetType(Integer)))

        Dim desayunoParameter As ObjectParameter = If(desayuno.HasValue, New ObjectParameter("desayuno", desayuno), New ObjectParameter("desayuno", GetType(Integer)))

        Dim habitacion_sParameter As ObjectParameter = If(habitacion_s.HasValue, New ObjectParameter("habitacion_s", habitacion_s), New ObjectParameter("habitacion_s", GetType(Integer)))

        Dim habitacion_dParameter As ObjectParameter = If(habitacion_d.HasValue, New ObjectParameter("habitacion_d", habitacion_d), New ObjectParameter("habitacion_d", GetType(Integer)))

        Dim hotelParameter As ObjectParameter = If(hotel.HasValue, New ObjectParameter("hotel", hotel), New ObjectParameter("hotel", GetType(Integer)))

        Dim usuarioParameter As ObjectParameter = If(usuario.HasValue, New ObjectParameter("usuario", usuario), New ObjectParameter("usuario", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of Nullable(Of Integer))("reservar_vuelo_Hotel_p", destinoParameter, vueloParameter, pasajerosParameter, desayunoParameter, habitacion_sParameter, habitacion_dParameter, hotelParameter, usuarioParameter)
    End Function

    Public Overridable Function reservar_vuelo_Hotel_Traslado_e(destino As Nullable(Of Integer), vuelo As Nullable(Of Integer), pasajeros As Nullable(Of Integer), desayuno As Nullable(Of Integer), habitacion_s As Nullable(Of Integer), habitacion_d As Nullable(Of Integer), hotel As Nullable(Of Integer), usuario As Nullable(Of Integer)) As ObjectResult(Of Nullable(Of Integer))
        Dim destinoParameter As ObjectParameter = If(destino.HasValue, New ObjectParameter("destino", destino), New ObjectParameter("destino", GetType(Integer)))

        Dim vueloParameter As ObjectParameter = If(vuelo.HasValue, New ObjectParameter("vuelo", vuelo), New ObjectParameter("vuelo", GetType(Integer)))

        Dim pasajerosParameter As ObjectParameter = If(pasajeros.HasValue, New ObjectParameter("pasajeros", pasajeros), New ObjectParameter("pasajeros", GetType(Integer)))

        Dim desayunoParameter As ObjectParameter = If(desayuno.HasValue, New ObjectParameter("desayuno", desayuno), New ObjectParameter("desayuno", GetType(Integer)))

        Dim habitacion_sParameter As ObjectParameter = If(habitacion_s.HasValue, New ObjectParameter("habitacion_s", habitacion_s), New ObjectParameter("habitacion_s", GetType(Integer)))

        Dim habitacion_dParameter As ObjectParameter = If(habitacion_d.HasValue, New ObjectParameter("habitacion_d", habitacion_d), New ObjectParameter("habitacion_d", GetType(Integer)))

        Dim hotelParameter As ObjectParameter = If(hotel.HasValue, New ObjectParameter("hotel", hotel), New ObjectParameter("hotel", GetType(Integer)))

        Dim usuarioParameter As ObjectParameter = If(usuario.HasValue, New ObjectParameter("usuario", usuario), New ObjectParameter("usuario", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of Nullable(Of Integer))("reservar_vuelo_Hotel_Traslado_e", destinoParameter, vueloParameter, pasajerosParameter, desayunoParameter, habitacion_sParameter, habitacion_dParameter, hotelParameter, usuarioParameter)
    End Function

    Public Overridable Function reservar_vuelo_Hotel_Traslado_p(destino As Nullable(Of Integer), vuelo As Nullable(Of Integer), pasajeros As Nullable(Of Integer), desayuno As Nullable(Of Integer), habitacion_s As Nullable(Of Integer), habitacion_d As Nullable(Of Integer), hotel As Nullable(Of Integer), usuario As Nullable(Of Integer)) As ObjectResult(Of Nullable(Of Integer))
        Dim destinoParameter As ObjectParameter = If(destino.HasValue, New ObjectParameter("destino", destino), New ObjectParameter("destino", GetType(Integer)))

        Dim vueloParameter As ObjectParameter = If(vuelo.HasValue, New ObjectParameter("vuelo", vuelo), New ObjectParameter("vuelo", GetType(Integer)))

        Dim pasajerosParameter As ObjectParameter = If(pasajeros.HasValue, New ObjectParameter("pasajeros", pasajeros), New ObjectParameter("pasajeros", GetType(Integer)))

        Dim desayunoParameter As ObjectParameter = If(desayuno.HasValue, New ObjectParameter("desayuno", desayuno), New ObjectParameter("desayuno", GetType(Integer)))

        Dim habitacion_sParameter As ObjectParameter = If(habitacion_s.HasValue, New ObjectParameter("habitacion_s", habitacion_s), New ObjectParameter("habitacion_s", GetType(Integer)))

        Dim habitacion_dParameter As ObjectParameter = If(habitacion_d.HasValue, New ObjectParameter("habitacion_d", habitacion_d), New ObjectParameter("habitacion_d", GetType(Integer)))

        Dim hotelParameter As ObjectParameter = If(hotel.HasValue, New ObjectParameter("hotel", hotel), New ObjectParameter("hotel", GetType(Integer)))

        Dim usuarioParameter As ObjectParameter = If(usuario.HasValue, New ObjectParameter("usuario", usuario), New ObjectParameter("usuario", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of Nullable(Of Integer))("reservar_vuelo_Hotel_Traslado_p", destinoParameter, vueloParameter, pasajerosParameter, desayunoParameter, habitacion_sParameter, habitacion_dParameter, hotelParameter, usuarioParameter)
    End Function

    Public Overridable Function reservarVuelo(tipo As String, vuelo As String, destino As String, usuario As String, pasajeros As Nullable(Of Integer)) As ObjectResult(Of Nullable(Of Integer))
        Dim tipoParameter As ObjectParameter = If(tipo IsNot Nothing, New ObjectParameter("tipo", tipo), New ObjectParameter("tipo", GetType(String)))

        Dim vueloParameter As ObjectParameter = If(vuelo IsNot Nothing, New ObjectParameter("vuelo", vuelo), New ObjectParameter("vuelo", GetType(String)))

        Dim destinoParameter As ObjectParameter = If(destino IsNot Nothing, New ObjectParameter("destino", destino), New ObjectParameter("destino", GetType(String)))

        Dim usuarioParameter As ObjectParameter = If(usuario IsNot Nothing, New ObjectParameter("usuario", usuario), New ObjectParameter("usuario", GetType(String)))

        Dim pasajerosParameter As ObjectParameter = If(pasajeros.HasValue, New ObjectParameter("pasajeros", pasajeros), New ObjectParameter("pasajeros", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of Nullable(Of Integer))("reservarVuelo", tipoParameter, vueloParameter, destinoParameter, usuarioParameter, pasajerosParameter)
    End Function

    Public Overridable Function salida(query As String) As ObjectResult(Of salida_Result)
        Dim queryParameter As ObjectParameter = If(query IsNot Nothing, New ObjectParameter("query", query), New ObjectParameter("query", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of salida_Result)("salida", queryParameter)
    End Function

    Public Overridable Function ticket_crucero(factura As Nullable(Of Integer)) As ObjectResult(Of ticket_crucero_Result)
        Dim facturaParameter As ObjectParameter = If(factura.HasValue, New ObjectParameter("factura", factura), New ObjectParameter("factura", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of ticket_crucero_Result)("ticket_crucero", facturaParameter)
    End Function

    Public Overridable Function ticket_Vuelo_E(factura As Nullable(Of Integer)) As ObjectResult(Of ticket_Vuelo_E_Result)
        Dim facturaParameter As ObjectParameter = If(factura.HasValue, New ObjectParameter("factura", factura), New ObjectParameter("factura", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of ticket_Vuelo_E_Result)("ticket_Vuelo_E", facturaParameter)
    End Function

    Public Overridable Function ticket_Vuelo_Hotel(factura As Nullable(Of Integer)) As ObjectResult(Of ticket_Vuelo_Hotel_Result)
        Dim facturaParameter As ObjectParameter = If(factura.HasValue, New ObjectParameter("factura", factura), New ObjectParameter("factura", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of ticket_Vuelo_Hotel_Result)("ticket_Vuelo_Hotel", facturaParameter)
    End Function

    Public Overridable Function ubicar_crucero(query As String) As ObjectResult(Of ubicar_crucero_Result)
        Dim queryParameter As ObjectParameter = If(query IsNot Nothing, New ObjectParameter("query", query), New ObjectParameter("query", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of ubicar_crucero_Result)("ubicar_crucero", queryParameter)
    End Function

    Public Overridable Function vuelos(fecha As Nullable(Of Date), codigo_aeropuerto As Nullable(Of Integer), codigo_destino As Nullable(Of Integer), asientos As Nullable(Of Integer), tipo As Nullable(Of Integer)) As ObjectResult(Of vuelos_Result)
        Dim fechaParameter As ObjectParameter = If(fecha.HasValue, New ObjectParameter("fecha", fecha), New ObjectParameter("fecha", GetType(Date)))

        Dim codigo_aeropuertoParameter As ObjectParameter = If(codigo_aeropuerto.HasValue, New ObjectParameter("codigo_aeropuerto", codigo_aeropuerto), New ObjectParameter("codigo_aeropuerto", GetType(Integer)))

        Dim codigo_destinoParameter As ObjectParameter = If(codigo_destino.HasValue, New ObjectParameter("codigo_destino", codigo_destino), New ObjectParameter("codigo_destino", GetType(Integer)))

        Dim asientosParameter As ObjectParameter = If(asientos.HasValue, New ObjectParameter("asientos", asientos), New ObjectParameter("asientos", GetType(Integer)))

        Dim tipoParameter As ObjectParameter = If(tipo.HasValue, New ObjectParameter("tipo", tipo), New ObjectParameter("tipo", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of vuelos_Result)("vuelos", fechaParameter, codigo_aeropuertoParameter, codigo_destinoParameter, asientosParameter, tipoParameter)
    End Function

End Class
